import { CssBaseline, ThemeProvider } from "@mui/material";
import type { Metadata } from "next";
import theme from "./styles/theme/theme";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeProvider theme={theme}>
        <CssBaseline enableColorScheme />
        <body>{children}</body>
      </ThemeProvider>
    </html>
  );
}
